// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_hire_air_hostess_ulla = "CgkI-6iB1dkDEAIQBQ"; // <GPGSID>
        public const string achievement_buy_fighter_z3 = "CgkI-6iB1dkDEAIQBA"; // <GPGSID>
        public const string achievement_buy_private_jet = "CgkI-6iB1dkDEAIQAw"; // <GPGSID>
        public const string achievement_hire_air_hostess_mary = "CgkI-6iB1dkDEAIQBg"; // <GPGSID>
        public const string leaderboard_scores = "CgkI-6iB1dkDEAIQAQ"; // <GPGSID>
        public const string achievement_buy_helicopter = "CgkI-6iB1dkDEAIQAg"; // <GPGSID>
        public const string achievement_build_three_air_control_towers = "CgkI-6iB1dkDEAIQCA"; // <GPGSID>
        public const string achievement_make_full_prestige = "CgkI-6iB1dkDEAIQBw"; // <GPGSID>

}

